version: "2.4"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=go_example_db
      - POSTGRES_PASSWORD=go_example_db
    ports:
      - 5432:5432
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
